[phases.setup]
nixPkgs = ['...', 'php82']

[phases.build]
cmds = [
    'composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[phases.start]
cmds = [
    'php artisan storage:link --force',
    'apache2-foreground'
]
